#!/bin/bash
# Generate execution report from job logs

WORKSPACE=${1:-~/workspace}
JOB_ID=$2
OUTPUT_FILE=${3:-report_${JOB_ID}.md}

if [[ -z "$JOB_ID" ]]; then
    echo "Usage: $0 <workspace> <job_id> [output_file]"
    echo ""
    echo "Example:"
    echo "  $0 ~/workspace j_abc123 report.md"
    exit 1
fi

JOB_DIR="$WORKSPACE/jobs/$JOB_ID"

if [[ ! -d "$JOB_DIR" ]]; then
    echo "❌ Job directory not found: $JOB_DIR"
    exit 1
fi

# Collect data
JOB_SPEC=$(cat "$JOB_DIR/job.yaml" 2>/dev/null || echo "N/A")
LATEST_LOG=$(ls -t "$JOB_DIR/logs/"*.jsonl 2>/dev/null | head -1)

# Generate report
cat > "$OUTPUT_FILE" << EOF
# Concierge Execution Report

**Job ID**: $JOB_ID
**Workspace**: $WORKSPACE
**Generated**: $(date)

## Job Summary

EOF

# Status
if [[ -n "$JOB_SPEC" ]]; then
    STATUS=$(echo "$JOB_SPEC" | grep "status:" | awk '{print $2}')
    CREATED=$(echo "$JOB_SPEC" | grep "created_at:" | awk '{print $2}')

    cat >> "$OUTPUT_FILE" << EOF
- **Status**: $STATUS
- **Created**: $CREATED

EOF
fi

# Timeline
if [[ -n "$LATEST_LOG" ]]; then
    cat >> "$OUTPUT_FILE" << EOF
## Timeline

EOF

    # Extract key events
    jq -r 'select(.type | contains("job") or contains("step")) | "\(.timestamp) - \(.type)"' \
        "$LATEST_LOG" 2>/dev/null | while read -r line; do
        echo "- $line" >> "$OUTPUT_FILE"
    done
fi

# Step details
if [[ -n "$LATEST_LOG" ]]; then
    cat >> "$OUTPUT_FILE" << EOF

## Step Execution Details

EOF

    jq -r 'select(.type == "step.completed") |
        "### Step: \(.payload.step_id)\n- Status: COMPLETED\n- Duration: \(.payload.duration)s\n"' \
        "$LATEST_LOG" 2>/dev/null >> "$OUTPUT_FILE"
fi

# Artifacts
if [[ -d "$JOB_DIR/artifacts" ]]; then
    cat >> "$OUTPUT_FILE" << EOF

## Artifacts Generated

EOF

    ls -lh "$JOB_DIR/artifacts/" 2>/dev/null | tail -n +2 | while read -r line; do
        size=$(echo "$line" | awk '{print $5}')
        file=$(echo "$line" | awk '{print $NF}')
        echo "- **$file** ($size)" >> "$OUTPUT_FILE"
    done
fi

# Statistics
if [[ -n "$LATEST_LOG" ]]; then
    cat >> "$OUTPUT_FILE" << EOF

## Execution Statistics

EOF

    TOTAL_EVENTS=$(jq 'length' "$LATEST_LOG" 2>/dev/null || echo "0")
    ERROR_COUNT=$(grep -c '"type":".*error"' "$LATEST_LOG" 2>/dev/null || echo "0")

    echo "- **Total Events**: $TOTAL_EVENTS" >> "$OUTPUT_FILE"
    echo "- **Errors**: $ERROR_COUNT" >> "$OUTPUT_FILE"
fi

# Raw logs
cat >> "$OUTPUT_FILE" << EOF

## Raw Event Log

\`\`\`
EOF

# Append formatted logs
if [[ -n "$LATEST_LOG" ]]; then
    tail -20 "$LATEST_LOG" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << EOF
\`\`\`

---
*Report generated by Concierge $(date)*
EOF

echo "✓ Report generated: $OUTPUT_FILE"
echo ""
echo "=== Report Preview ==="
head -40 "$OUTPUT_FILE"
